language: go

sudo: required

go:
  - "1.10.x"

services:
  - redis

before_install:
  - git clone git@github.com:beanstalkd/beanstalkd.git
  - cd beanstalk
  - make
  - /beanstalkd &
  - cd ../
  - go version
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install -y php7.1-cli php7.1-xml php7.1-xdebug php7.1-dom
  - sudo cp `which php7.1` `which php`
  - go get ./...
  - go build -o rr tests/main.go

install:
  - sudo cp `which php7.1` `which php`
  - php -v
  - composer self-update
  - composer install --no-interaction --ignore-platform-reqs

before_script:
  - ./rr serve --config tests/.rr.yaml &

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml