language: go

sudo: required

go:
  - "1.10.x"

before_install:
  - go version
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install -y php7.1-cli
  - sudo cp `which php7.1` `which php`
  - php -v
  - composer self-update

install:
  - composer install --no-interaction
  - go build cmd/main.go -o rr

before_script:
  - ./rr serve -v -d --config = cmd/.rr.yaml &

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml