language: php

php:
  - 7.1
  - 7.2
  - nightly

go:
  - 1.9

before_install:
  - composer self-update

install:
  - composer install --no-interaction
  - go version
  - go get "github.com/spiral/jobs"
  - cp -r * $GOPATH/src/github.com/spiral/jobs
  - go build cmd/main.go -o rr

before_script:
  - ./rr serve -v -d --config = cmd/.rr.yaml &

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml